language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO="django>=1.11,<2" CMS="django-cms>=3.6,<3.7"
  - DJANGO="django>=2,<2.1" CMS="django-cms>=3.6,<3.7"
  - DJANGO="django>=2.1,<2.2" CMS="django-cms>=3.6,<3.7"
  - TOXENV=lint

matrix:
  exclude:
  - python: "3.5"
    env: DJANGO="django>=1.7,<1.8" CMS="django-cms>=3.2,<3.3"
  - python: "3.3"
    env: TOXENV=lint
  - python: "3.4"
    env: TOXENV=lint
install:
  - "pip install setuptools -U"
  - "pip install $DJANGO $CMS"
script:
  - make travis
after_success:
  - coveralls
